unload and blacklist kernel dvb drivers
sometimes librtlsdr cannot acquire usb interface

diff --git a/src/main/deb/postinst b/src/main/deb/postinst
--- a/src/main/deb/postinst
+++ b/src/main/deb/postinst
@@ -4,8 +4,16 @@ ${config.installDir}/lib/download.sh ${config.installDir}/lib/ /usr/share/java/r
 chown ${config.user}:${config.group} ${config.installDir}/lib/*.jar /usr/share/java/r2cloud/*.jar
 chmod 640 ${config.installDir}/lib/*.jar /usr/share/java/r2cloud/*.jar
 
-cp ${config.installDir}/etc/r2cloud.service /etc/systemd/system/r2cloud.service;
+cp ${config.installDir}/etc/r2cloud.service /etc/systemd/system/r2cloud.service
 cp ${config.installDir}/etc/.wxtoimglic /home/pi/
+
+# try unload modules. if module in use, then modprobe return non-zero status. ignore it
+modprobe --remove rtl2832 || true
+echo "blacklist rtl2832" >> /etc/modprobe.d/r2cloud-blacklist.conf
+modprobe --remove dvb_usb_rtl28xxu || true
+echo "blacklist dvb_usb_rtl28xxu" >> /etc/modprobe.d/r2cloud-blacklist.conf
+modprobe --remove e4000 || true
+echo "blacklist e4000" >> /etc/modprobe.d/r2cloud-blacklist.conf
 
 systemctl enable r2cloud.service
 if [ -d /run/systemd/system ]; then
